<a href="https://colab.research.google.com/github/hossamAhmedSalah/EGYPT/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np
a = np.array([1, 2, 3])
print(a)


[1 2 3]


In [8]:
b = np.array( [[0.1, 0.4, 0.7], [6.2, 5.0, 4.1]])
print(b)


[[0.1 0.4 0.7]
 [6.2 5.  4.1]]


In [11]:
#get dimensions
a.ndim #1
b.ndim #2


2

In [12]:
#get shape
a.shape


(3,)

In [13]:
b.shape


(2, 3)

In [29]:
#get type
a.dtype #dtype('int64') can change=> a = np.array([1, 2, 3], dtype='int32')

dtype('int64')

In [28]:
#get size
a.itemsize #8 byte when it's 64 SIZE of one element X/8 byte

8

In [33]:
#get total size
a.size * a.itemsize

24

In [34]:
a.nbytes

24

In [35]:
b.itemsize

8

In [36]:
b.size * b.itemsize

48

In [37]:
b.nbytes

48

In [39]:
b.dtype

dtype('float64')

In [102]:
c = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]] )
#get a specific element [r, c]
c[1,5] #13
c[0,5] #6
c[-1,-1]#14
c[-1,-4]#11
c[1,-4]#11
#get a specific raw
c[0] #first raw  array([1, 2, 3, 4, 5, 6, 7])
c[1] #seconed raw array([ 8,  9, 10, 11, 12, 13, 14])
c[0, :2] # to 2 column [1,2] :numberOFColumn
c[:2,:3] 
c[::-1] # reverse the matrix
c[:, 5] # array([ 6, 13])
# [strartindex: endindex: stepsize]
c[0, 0:6:2] #array([1, 3, 5])
c[1, 3:6:2] #array([11, 13])
c[1, 3:6:3] #array([11]) 11=>14?❌
c[1, 3:7:3] #array([11, 14])⭐
c[1, 2:-1:1] #array([10, 11, 12, 13])
#you can change elements
print("c before any change\n", c)
c[1,4] = 100
print("\n",c[1,4],"\n")
print(c)




c before any change
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

 100 

[[  1   2   3   4   5   6   7]
 [  8   9  10  11 100  13  14]]


In [131]:
d = np.array([  [[1,9,7],[2,4,6],[3,6,9]]  ])
d.shape
print(d,"\n")
d[0,2,2]#9


[[[1 9 7]
  [2 4 6]
  [3 6 9]]] 



9

In [146]:
#all 0s matrix
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [147]:
#all 1s matrix
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [151]:
#matrix of any other numbers
np.full((3,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [155]:
#full-like #like a previous array that you had
np.full((a.shape), 6)

array([6, 6, 6])

In [198]:
from numpy.core.fromnumeric import shape
#Random decimal number
np.random.rand(4,5)*10
np.floor(np.random.rand(4,5)*10)+1 #random numbers from 0+1~10
np.random.randint(7,56, size=(3,3))




array([[48, 37,  7],
       [21, 53, 14],
       [30, 55, 46]])

In [203]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])